# Changes here will be overwritten by Copier
_commit: b6bd6c7
_src_path: git@github.com:python-project-templates/base.git
add_extension: python
email: 3105306+timkpaine@users.noreply.github.com
github: python-project-templates
project_description: Hatch plugin for C++ builds
project_name: hatch cpp
python_version_primary: '3.11'
team: the hatch-cpp authors
